version: 0.0
os: linux
files:
  - source: /target/RooT.war
    destination: /opt/tomcat/webapps/RooT.war   # 루트(/)로 서비스
    owner: tomcat
    group: tomcat
permissions:
  - object: /opt/tomcat/webapps/RooT.war
    owner: tomcat
    group: tomcat
    mode: 644
hooks:
  BeforeInstall:
    - location: scripts/stop_tomcat.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: scripts/deploy_war.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start_tomcat.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: root
