version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21   # 또는 corretto17 (프로젝트 JDK에 맞춰 조정)
    commands:
      - echo "Install phase"
      - mvn -v
  pre_build:
    commands:
      - echo "Run unit tests"
      - mvn -B -U -DskipTests=false test
  build:
    commands:
      - echo "Package WAR"
      - mvn -B -U -DskipTests=false clean package
  post_build:
    commands:
      - echo "Prepare artifacts"
      - mkdir -p output
      # 프로젝트 패키징이 war 인 경우 target/*.war 존재
      - ls -al target || true
      # 루트 경로 배포를 염두에 두고 ROOT.war로 이름 고정 (원하면 myapp.war 유지)
      - WAR_FILE=$(ls target/*.war | head -n1)
      - cp "$WAR_FILE" output/ROOT.war
      - echo "Done: $(ls -al output)"
artifacts:
  files:
    - output/ROOT.war
  name: myapp-war-$(date +%Y%m%d%H%M%S)
  discard-paths: yes
cache:
  paths:
    - "/root/.m2/**/*"

