version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21   # 또는 corretto17 (프로젝트 JDK에 맞춰 조정)
    commands:
      - echo "Install phase"
      - mvn -v
  pre_build:
    commands:
      - echo "Run unit tests"
      - mvn -B -U -DskipTests=false test
  build:
    commands:
      - echo "Package WAR"
      - mvn -B -U -DskipTests=false clean package
  post_build:
    commands:
      - echo "Prepare artifacts"
      - mkdir -p output
      # 프로젝트 패키징이 war 인 경우 target/*.war 존재
      - ls -al target || true
      - |
          set -euo pipefail
          # WAR 탐색
          WAR_FILE=$(ls -1 target/*.war 2>/dev/null | head -n1 || true)
          if [ -z "${WAR_FILE:-}" ]; then
            echo "No WAR found in target/"; exit 1
          fi
          # ROOT.war로 복사
          cp "$WAR_FILE" output/ROOT.war
          echo "Done:"
          ls -al output
artifacts:
  files:
    - output/ROOT.war
  discard-paths: yes
cache:
  paths:
    - "/root/.m2/**/*"

